config/routes.rb
Rails.application.routes.draw do
  # get 'main/index'
  match 'work', to:'work#index', :via=>'get'
  root 'main#about'

  resources :values
  resources :themes
  # resources :microposts
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do

    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: 'get'

  end
  
  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  # match 'help',     to: 'main#help',            via: 'get'
  # match 'contacts', to: 'main#contacts',        via: 'get'

  # match 'work', to:'work#index', :via=>'get'
  match 'work/choose_theme', to:'work#choose_theme', :via=>'get'
  match 'work/display_theme', to:'work#display_theme', :via=>'post'

  # match 'work', to:'work#index', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'
end

app/models/user.rb
class User < ApplicationRecord
	has_many :values, dependent: :destroy

	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true,
	     uniqueness: { case_sensitive: false },
	     format: { with: VALID_EMAIL_REGEX }

	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label t('.name')
    = f.text_field :name
  .field
    = f.label t('.email')
    = f.text_field :email
  .field
    = f.label t('.password')
    = f.password_field :password
  .field
    = f.label t('.password_confirmation')
    = f.password_field :password_confirmation


  .actions
    = f.submit t(".create_account"), class: "btn btn-large btn-primary"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
/ \|
/ = link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
-#%h1 =t(".new_user")
%h1 Новый пользователь

= render 'form'

/ = link_to 'Back', users_path

app/views/users/show.html.haml
.text-center
	%h1
		/ = gravatar_for @user
		= @user.name
	%p
		%b= t('.email')
		= @user.email

	= link_to t('.work'), work_path, class: "btn btn-lg btn-primary"