config/routes.rb
Rails.application.routes.draw do
  # get 'main/index'
  match 'work', to:'work#index', :via=>'get'
  root 'main#about'

  resources :values
  resources :themes
  # resources :microposts
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do

    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: 'get'

  end
  
  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  # match 'help',     to: 'main#help',            via: 'get'
  # match 'contacts', to: 'main#contacts',        via: 'get'

  # match 'work', to:'work#index', :via=>'get'
  match 'work/choose_theme', to:'work#choose_theme', :via=>'get'
  match 'work/display_theme', to:'work#display_theme', :via=>'post'

  # match 'work', to:'work#index', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'
end

app/views/shared/_footer.html.haml
%footer.navbar-fixed-bottom
	.text-center
		= t(".Experteese")
		%span &#169;
		%span 2017

app/views/shared/_header.html.haml
%header
  %nav.navbar.navbar-inverse
    .container
      .container-fluid
        .navbar-header
          %p.locale
          -#.ru_link
          = link_to image_tag("ru_flag.png", alt: "", style: "width:18%; padding-right:5px;", title: "Русский" ), locale: :ru
          = link_to image_tag("en_flag.png", alt: "",  style: "width:20%", title: "English"), locale: :en
          %b
            = I18n.locale
        %ul.nav.navbar-nav
          %li
            =link_to t('.home'), about_path
        %ul.nav.navbar-nav.pull-right
          -if signed_in?
            %li
              = link_to t('.work'), work_path

            / %li 
            / #{current_user.name}
            / = gravatar_for current_user
            %li
              = link_to t('.profile'), current_user
            / %li.divider
            %li
              = link_to t('.sign_out'), signout_path, method: "delete"
          -else
            %li= link_to t('.sign_in'), signin_path