config/routes.rb
Rails.application.routes.draw do
  # get 'main/index'
  match 'work', to:'work#index', :via=>'get'
  root 'main#about'

  resources :values
  resources :themes
  # resources :microposts
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do

    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: 'get'

  end
  
  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  # match 'help',     to: 'main#help',            via: 'get'
  # match 'contacts', to: 'main#contacts',        via: 'get'

  # match 'work', to:'work#index', :via=>'get'
  match 'work/choose_theme', to:'work#choose_theme', :via=>'get'
  match 'work/display_theme', to:'work#display_theme', :via=>'post'

  # match 'work', to:'work#index', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :theme
  scope :theme_images, -> (theme_id) { select('id','name','file','ave_value').where(theme_id: theme_id) }

  # find image by id
  scope :find_image, -> (image_id) { find(image_id) }

  def self.value_and_update(new_value_data)
    image_id = new_value_data[:image_id]
    Value.create(new_value_data)
    ave_value = Value.calc_average_value(image_id)
    logger.info "In image.rb ave_value = #{ave_value.inspect}"
    update_ave_value(image_id, ave_value)
    show_valued_image(new_value_data)
  end

  def self.update_ave_value(image_id, ave_value)
    image = find(image_id)
    image.update(ave_value: ave_value)
  end

# new_value_data is from work_image.rb module
  def self.show_valued_image(new_value_data)
    image_id = new_value_data[:image_id]
    theme_id = new_value_data[:theme_id]
    logger.info "IN eimg.rb theme_id = #{theme_id.inspect}"
    current_user_id = new_value_data[:user_id]
    user_valued, value = Value.user_valued_exists(current_user_id, image_id) # 1/0 ?
    values_qty = Value.all.count.round
  
    if user_valued == 1
      common_ave_value = find(image_id).ave_value.round
    else
      common_ave_value = 0
    end
  
    data = {
      values_qty: values_qty,
      current_user_id: current_user_id,
      theme_id: theme_id,
      image_id: image_id,
      user_valued: user_valued,
      value: value,
      common_ave_value: common_ave_value
    }
    logger.info "In show_image:  data = #{data.inspect} "
    data
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :file, :ave_value)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.haml
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.text_field :file
  .field
    = f.label :ave_value
    = f.text_field :ave_value
  .actions
    = f.submit 'Save'

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table
  %thead
    %tr
      %th Name
      %th File
      %th Av value
      %th
      %th
      %th

  %tbody
    - @images.each do |image|
      %tr
        %td= image.name
        %td= image.file
        %td= image.ave_value
        %td= link_to 'Show', image
        %td= link_to 'Edit', edit_image_path(image)
        %td= link_to 'Destroy', image, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @image.name
%p
  %b File:
  = @image.file
%p
  %b Av value:
  = @image.ave_value

= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path